name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: Snyk IaC test
        run: | 
          terraform plan -out=tfplan
          terraform show --json tfplan > tfplan.json
          snyk iac test tfplan.json --experimental 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
